# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 22:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchase_datetime', models.DateTimeField(default=datetime.datetime(2017, 12, 15, 0, 45, 58, 396000))),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guitar',
            fields=[
                ('guitar_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('producer', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('color', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shop_type', models.CharField(max_length=255)),
                ('shop_name', models.CharField(max_length=255)),
                ('shop_description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarsapp.Customer'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_guitar_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarsapp.Guitar'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_shop_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guitarsapp.Shop'),
        ),
    ]
