# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 23:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitarsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bill',
            name='purchase_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 15, 1, 24, 51, 261000)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='guitar',
            name='guitar_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
